package com.sample.mvc.Entity;

public class EqpCha {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eqp_cha.id
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eqp_cha.eid
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private Integer eid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eqp_cha.type
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eqp_cha.node
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private Integer node;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eqp_cha.uid
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eqp_cha.name
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eqp_cha.ext1
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private Integer ext1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eqp_cha.ext2
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private Integer ext2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eqp_cha.resid
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private Integer resid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eqp_cha.id
	 * @return  the value of eqp_cha.id
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eqp_cha.id
	 * @param id  the value for eqp_cha.id
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eqp_cha.eid
	 * @return  the value of eqp_cha.eid
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public Integer getEid() {
		return eid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eqp_cha.eid
	 * @param eid  the value for eqp_cha.eid
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setEid(Integer eid) {
		this.eid = eid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eqp_cha.type
	 * @return  the value of eqp_cha.type
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eqp_cha.type
	 * @param type  the value for eqp_cha.type
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eqp_cha.node
	 * @return  the value of eqp_cha.node
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public Integer getNode() {
		return node;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eqp_cha.node
	 * @param node  the value for eqp_cha.node
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setNode(Integer node) {
		this.node = node;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eqp_cha.uid
	 * @return  the value of eqp_cha.uid
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eqp_cha.uid
	 * @param uid  the value for eqp_cha.uid
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setUid(String uid) {
		this.uid = uid == null ? null : uid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eqp_cha.name
	 * @return  the value of eqp_cha.name
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eqp_cha.name
	 * @param name  the value for eqp_cha.name
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eqp_cha.ext1
	 * @return  the value of eqp_cha.ext1
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public Integer getExt1() {
		return ext1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eqp_cha.ext1
	 * @param ext1  the value for eqp_cha.ext1
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setExt1(Integer ext1) {
		this.ext1 = ext1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eqp_cha.ext2
	 * @return  the value of eqp_cha.ext2
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public Integer getExt2() {
		return ext2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eqp_cha.ext2
	 * @param ext2  the value for eqp_cha.ext2
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setExt2(Integer ext2) {
		this.ext2 = ext2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eqp_cha.resid
	 * @return  the value of eqp_cha.resid
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public Integer getResid() {
		return resid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eqp_cha.resid
	 * @param resid  the value for eqp_cha.resid
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setResid(Integer resid) {
		this.resid = resid;
	}
}