package com.sample.mvc.Entity;

public class Equipment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.id
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.no
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private Integer no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.type
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.ip
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.port
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private Integer port;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.user
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private String user;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.pass
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private String pass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.name
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.id
	 * @return  the value of equipment.id
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.id
	 * @param id  the value for equipment.id
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.no
	 * @return  the value of equipment.no
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public Integer getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.no
	 * @param no  the value for equipment.no
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setNo(Integer no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.type
	 * @return  the value of equipment.type
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.type
	 * @param type  the value for equipment.type
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.ip
	 * @return  the value of equipment.ip
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.ip
	 * @param ip  the value for equipment.ip
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.port
	 * @return  the value of equipment.port
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.port
	 * @param port  the value for equipment.port
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.user
	 * @return  the value of equipment.user
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public String getUser() {
		return user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.user
	 * @param user  the value for equipment.user
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setUser(String user) {
		this.user = user == null ? null : user.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.pass
	 * @return  the value of equipment.pass
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public String getPass() {
		return pass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.pass
	 * @param pass  the value for equipment.pass
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setPass(String pass) {
		this.pass = pass == null ? null : pass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.name
	 * @return  the value of equipment.name
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.name
	 * @param name  the value for equipment.name
	 * @mbggenerated  Tue Dec 11 10:33:02 CST 2012
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}