package com.sample.mvc.Entity;

public class Resource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.id
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.pid
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.class
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	private Integer cls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.type
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.name
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.state
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.ord
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	private Integer ord;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.id
	 * @return  the value of resource.id
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.id
	 * @param id  the value for resource.id
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.pid
	 * @return  the value of resource.pid
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.pid
	 * @param pid  the value for resource.pid
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.class
	 * @return  the value of resource.class
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public Integer getCls() {
		return cls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.class
	 * @param cls  the value for resource.class
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public void setCls(Integer cls) {
		this.cls = cls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.type
	 * @return  the value of resource.type
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.type
	 * @param type  the value for resource.type
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.name
	 * @return  the value of resource.name
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.name
	 * @param name  the value for resource.name
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.state
	 * @return  the value of resource.state
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.state
	 * @param state  the value for resource.state
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.ord
	 * @return  the value of resource.ord
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public Integer getOrd() {
		return ord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.ord
	 * @param ord  the value for resource.ord
	 * @mbggenerated  Tue Nov 06 16:43:41 CST 2012
	 */
	public void setOrd(Integer ord) {
		this.ord = ord;
	}
}