package com.sample.mvc.Entity;

public class ResType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_type.id
     *
     * @mbggenerated Thu Dec 20 14:21:33 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_type.name
     *
     * @mbggenerated Thu Dec 20 14:21:33 CST 2012
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_type.id
     *
     * @return the value of res_type.id
     *
     * @mbggenerated Thu Dec 20 14:21:33 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_type.id
     *
     * @param id the value for res_type.id
     *
     * @mbggenerated Thu Dec 20 14:21:33 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_type.name
     *
     * @return the value of res_type.name
     *
     * @mbggenerated Thu Dec 20 14:21:33 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_type.name
     *
     * @param name the value for res_type.name
     *
     * @mbggenerated Thu Dec 20 14:21:33 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}