package com.sample.db.model;

public class JsonTest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column json_test.id
	 * @mbggenerated  Tue Jan 19 15:20:17 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column json_test.jsonStr
	 * @mbggenerated  Tue Jan 19 15:20:17 CST 2016
	 */
	private Object jsonstr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column json_test.name
	 * @mbggenerated  Tue Jan 19 15:20:17 CST 2016
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column json_test.id
	 * @return  the value of json_test.id
	 * @mbggenerated  Tue Jan 19 15:20:17 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column json_test.id
	 * @param id  the value for json_test.id
	 * @mbggenerated  Tue Jan 19 15:20:17 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column json_test.jsonStr
	 * @return  the value of json_test.jsonStr
	 * @mbggenerated  Tue Jan 19 15:20:17 CST 2016
	 */
	public Object getJsonstr() {
		return jsonstr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column json_test.jsonStr
	 * @param jsonstr  the value for json_test.jsonStr
	 * @mbggenerated  Tue Jan 19 15:20:17 CST 2016
	 */
	public void setJsonstr(Object jsonstr) {
		this.jsonstr = jsonstr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column json_test.name
	 * @return  the value of json_test.name
	 * @mbggenerated  Tue Jan 19 15:20:17 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column json_test.name
	 * @param name  the value for json_test.name
	 * @mbggenerated  Tue Jan 19 15:20:17 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}