package com.sample.db.model;

import java.io.Serializable;

public class Permission implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.id
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.parentId
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private Integer parentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.name
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.url
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.type
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.describe
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private String describe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.weight
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private Byte weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.status
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.createTime
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private String createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.updateTime
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private String updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.id
	 * @return  the value of permission.id
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.id
	 * @param id  the value for permission.id
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.parentId
	 * @return  the value of permission.parentId
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public Integer getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.parentId
	 * @param parentid  the value for permission.parentId
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.name
	 * @return  the value of permission.name
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.name
	 * @param name  the value for permission.name
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.url
	 * @return  the value of permission.url
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.url
	 * @param url  the value for permission.url
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.type
	 * @return  the value of permission.type
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.type
	 * @param type  the value for permission.type
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.describe
	 * @return  the value of permission.describe
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public String getDescribe() {
		return describe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.describe
	 * @param describe  the value for permission.describe
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setDescribe(String describe) {
		this.describe = describe == null ? null : describe.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.weight
	 * @return  the value of permission.weight
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public Byte getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.weight
	 * @param weight  the value for permission.weight
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setWeight(Byte weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.status
	 * @return  the value of permission.status
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.status
	 * @param status  the value for permission.status
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.createTime
	 * @return  the value of permission.createTime
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.createTime
	 * @param createtime  the value for permission.createTime
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime == null ? null : createtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.updateTime
	 * @return  the value of permission.updateTime
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.updateTime
	 * @param updatetime  the value for permission.updateTime
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime == null ? null : updatetime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", parentid=").append(parentid);
		sb.append(", name=").append(name);
		sb.append(", url=").append(url);
		sb.append(", type=").append(type);
		sb.append(", describe=").append(describe);
		sb.append(", weight=").append(weight);
		sb.append(", status=").append(status);
		sb.append(", createtime=").append(createtime);
		sb.append(", updatetime=").append(updatetime);
		sb.append("]");
		return sb.toString();
	}
}