package com.sample.db.model;

import java.io.Serializable;

public class RolePermissionLinkKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission_link.roleId
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private Integer roleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission_link.permissionId
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	private Integer permissionid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission_link.roleId
	 * @return  the value of role_permission_link.roleId
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission_link.roleId
	 * @param roleid  the value for role_permission_link.roleId
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission_link.permissionId
	 * @return  the value of role_permission_link.permissionId
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public Integer getPermissionid() {
		return permissionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission_link.permissionId
	 * @param permissionid  the value for role_permission_link.permissionId
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	public void setPermissionid(Integer permissionid) {
		this.permissionid = permissionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission_link
	 * @mbggenerated  Thu Jan 21 15:12:39 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", roleid=").append(roleid);
		sb.append(", permissionid=").append(permissionid);
		sb.append("]");
		return sb.toString();
	}
}